# Generated by Django 3.2.3 on 2021-08-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='kusun adini yaziniz', max_length=127, unique=True, verbose_name='kurs adi')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='courses.jpg', null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
