# Generated by Django 3.2.3 on 2021-08-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tag',
            new_name='tags',
        ),
    ]
